# Setup
title:               DTedT.com
tagline:             'The professional website of David Ted Tarnovski'
description:         'The professional website of David Ted Tarnovski'
url:                 https://dted
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              David "Ted" Tarnovski
  url:               https://dtedt.com
  email:             Ted@dtedt.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
