# Setup
title:               DTedT.com
tagline:             'A weblog'
description:         'The professional website of David Ted Tarnovski'
url:                 http://dtedt.github.io
baseurl:             'http://dtedt.github.io/'
paginate:            5
permalink:           pretty

author: David "Ted" Tarnovski


# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
