# Setup
title:               DTedT.com
tagline:             'A Web Blog'
description:         'This is where I track my technical projects.'
url:                 http://dtedt.com
baseurl:             ''
paginate:            5
permalink:           pretty



# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
