const contacts = [
  { id: 1, 
   name: "Cam", 
   email: "cam@crabs.sand", 
   website: "www.cam.com",
   games: "Oswego: Quest For The Golden Pin", "Terry Groose Eats Sand",
   wip: "untitled card game",
   roles: "Writer", "Game Designer"
  },
  { id: 2, 
   name: "Ted Tarnovski", 
   email: "ted@dtedt.com", 
   games: "Seer Of Stars", 
   wip: "Fend",
   roles: "Producer", "QA Tester", 
  },
  { id: 3,
   name: "Jovan Kouakou",
   email: "jovan@jovankouakou.com",
   games: "Seer Of Stars",
   wip: null,
   roles: "Illustrator", "Web Designer", "SEO",
  },
  { id: ,
   name: ,
   email:,
   games: ,
   wip: ,
   roles: ,
];


const games = [
  { id: 1,
   img: "/img/1a.jpg",
   title: "Oswego: Quest For The Golden Pin",
   engine: "GBStudio",
   platforms: "Itch.io", "Steam",
   genre: "Top-down", "Adventure",
   link: "https://store.steampowered.com/app/4211310/Oswego_Quest_for_the_Golden_Pin/",
  },
  { id: 2,
   img: "",
   title: "Terry Groose Eats Sand",
   engine: "Godot",
   platforms: "Itch.io",
   genre: "Clicker",
   link: "",
  },
  { id: 3,
   img: "",
   title: "Seer Of Stars",
   engine: ,
   platforms: ,
   genre: ,
   link: ,
  }, 
    { id: ,
   img: ,
   title: ,
   engine: ,
   platforms: ,
   genre: ,
   link: ,
  }, 
    { id: ,
   img: ,
   title: ,
   engine: ,
   platforms: ,
   genre: ,
   link: ,
  }, 
    { id: ,
   img: ,
   title: ,
   engine: ,
   platforms: ,
   genre: ,
   link: ,
  }, 

  ];
